### ISSUE TITLE
Can't deploy my cdk stack

### ISSUE THREAD

**Issue by mdere** [localstack/aws-cdk-local#37]
I am new to cdk and this is the error message i am getting. Let me know if you need more info:

```
localstack_1  | 2021-01-23T17:03:28:INFO:localstack.utils.cloudformation.template_deployer: Updating resource apiv1OPTIONS44612F12 of type ApiGateway::Method
localstack_1  | 2021-01-23T17:03:28:INFO:localstack.utils.cloudformation.template_deployer: Unable to apply change set CDK-e97a2753-62b8-4b06-9ba3-9b0ff8df78fd: Parameter validation failed:
localstack_1  | Invalid type for parameter integrationHttpMethod, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
localstack_1  | Invalid type for parameter uri, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
localstack_1  | 2021-01-23T17:03:28:ERROR:cloudformation_api: Exception on / [POST]
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
localstack_1  |     response = self.full_dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
localstack_1  |     rv = self.handle_user_exception(e)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
localstack_1  |     reraise(exc_type, exc_value, tb)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack_1  |     raise value
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
localstack_1  |     rv = self.dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
localstack_1  |     return self.view_functions[rule.endpoint](**req.view_args)
localstack_1  |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_api.py", line 548, in handle_request
localstack_1  |     result = func(req_params)
localstack_1  |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_api.py", line 439, in execute_change_set
localstack_1  |     deployer.apply_change_set(change_set)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1743, in apply_change_set
localstack_1  |     change_set.changes = self.apply_changes(change_set.stack, change_set, stack_name=change_set.stack_name)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1960, in apply_changes
localstack_1  |     return self.apply_changes_in_loop(changes, old_stack, stack_name)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1996, in apply_changes_in_loop
localstack_1  |     self.apply_change(change, stack, new_resources, stack_name=stack_name)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 2048, in apply_change
localstack_1  |     result = update_resource(resource_id, new_resources, stack_name)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1170, in update_resource
localstack_1  |     return instance.update_resource(resource, stack_name=stack_name, resources=resources)
localstack_1  |   File "/opt/code/localstack/localstack/services/cloudformation/service_models.py", line 578, in update_resource
localstack_1  |     return client.put_integration(**kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
localstack_1  |     return self._make_api_call(operation_name, kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 648, in _make_api_call
localstack_1  |     request_dict = self._convert_to_request_dict(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 696, in _convert_to_request_dict
localstack_1  |     request_dict = self._serializer.serialize_to_request(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/validate.py", line 297, in serialize_to_request
localstack_1  |     raise ParamValidationError(report=report.generate_report())
localstack_1  | botocore.exceptions.ParamValidationError: Parameter validation failed:
localstack_1  | Invalid type for parameter integrationHttpMethod, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
localstack_1  | Invalid type for parameter uri, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```

**Comment by whummer** [comment]
Thanks for reporting @mdere . We've pushed a couple of fixes for API Gateway CloudFormation resources recently - can you please pull the `latest` image and confirm if this issue still persists? Thanks!
