### ISSUE TITLE
running cdklocal with solution constructs on localstack

### ISSUE THREAD

**Issue by ramayas** [localstack/aws-cdk-local#40]
Is it possible to run cdklocal with solution constructs at all? I created a sample cdklocal app with cdklocal init and added the aws @aws-solutions-constructs/aws-apigateway-lambda solution construct. Started the default localstack server  and ran cdklocal with the default cdklocal init example first. That worked so I know the setup works. The moment I switch over to the @aws-solutions-constructs/aws-apigateway-lambda solution construct I'm getting a Missing required parameter in input: "logGroupName". I've added a loggroupname on the apigatewway props function, to no success. Console message and code excerpt attached:

-------------------------------
console message:
------------------------------

Missing required parameter in input: "logGroupName"
2021-02-16T06:10:07:ERROR:cloudformation_api: Exception on / [POST]
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_api.py", line 548, in handle_request
    result = func(req_params)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_api.py", line 439, in execute_change_set
    deployer.apply_change_set(change_set)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1742, in apply_change_set
    change_set.changes = self.apply_changes(change_set.stack, change_set, stack_name=change_set.stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1959, in apply_changes
    return self.apply_changes_in_loop(changes, old_stack, stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1995, in apply_changes_in_loop
    self.apply_change(change, stack, new_resources, stack_name=stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 2043, in apply_change
    result = deploy_resource(resource_id, new_resources, stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1196, in deploy_resource
    return execute_resource_action(resource_id, resources, stack_name, ACTION_CREATE)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1269, in execute_resource_action
    result = configure_resource_via_sdk(resource_id, resources, resource_type, func, stack_name, action_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1378, in configure_resource_via_sdk
    raise e
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1375, in configure_resource_via_sdk
    result = function(**params)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 648, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 696, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/validate.py", line 293, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Missing required parameter in input: "logGroupName"

-----------------------
Code
-------------------------
 
         import { ApiGatewayToLambda } from '@aws-solutions-constructs/aws-apigateway-lambda';
          const devLogGroup = new cwlogs.LogGroup(this, "DevLogs",{
            logGroupName:'DevLogs'
        });
        const apigatewaylambda = new ApiGatewayToLambda(this, props.restApiID, {
            lambdaFunctionProps: {
                code: lambda.Code.fromAsset(`${__dirname}/lambdacode.zip`), 
                runtime: lambda.Runtime.NODEJS_12_X,
                functionName: 'getSpatDataTest',
                handler: 'main',
                memorySize: memsize,
                timeout: cdk.Duration.seconds(timeout)
            },
            apiGatewayProps: {
                proxy: true,
                deployOptions: {
                    stageName: 'dev',
                    accessLogDestination: new apigateway.LogGroupLogDestination(devLogGroup)

                },
                deploy: true,
                restApiName: props.restApiName,
                defaultMethodOptions: {
                    apiKeyRequired: false,
                    authorizationType: AuthorizationType.NONE,
                },
                binaryMediaTypes: ['*/*']
            }

        });

**Comment by ramayas** [comment]
I ran it with a non solution construct AWS ApiGateway and that seems to work exactly as documented. So I guess I answered my own question that this framework doesn't support yet....It'll be an awesome idea to support this....
