### ISSUE TITLE
I can't create the cloudformation changeset 

### ISSUE THREAD

**Issue by ismferd** [localstack/aws-cdk-local#44]
Hi, 

I'm trying to deploy a VPC through cdklocal, but I'm not be able to achieve it. If do you need more informatio about it, let me know.
**Command:**
```
AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test ../node_modules/aws-cdk-local/bin/cdklocal deploy localstack-vpc-stack
```
**Error:**
```
localstack-vpc-stack: deploying...
localstack-vpc-stack: creating CloudFormation changeset...

 ❌  localstack-vpc-stack failed: 500: 
    at Request.extractError (/Users/ismael/git/code/platform-infra-lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:55:29)
    at Request.callListeners (/Users/ismael/git/code/platform-infra-lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/ismael/git/code/platform-infra-lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/ismael/git/code/platform-infra-lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/ismael/git/code/platform-infra-lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/ismael/git/code/platform-infra-lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/ismael/git/code/platform-infra-lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/ismael/git/code/platform-infra-lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/ismael/git/code/platform-infra-lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/ismael/git/code/platform-infra-lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 500,
  time: 2021-03-17T17:46:12.186Z,
  requestId: undefined,
  statusCode: 500,
  retryable: true
}

```
**Localstack Image:**
```
localstack/localstack                                                                     latest                                                            28b721e18989   8 days ago      668MB
```

**Localstack logs:**
```
localstack_main | 2021-03-17T17:46:12:INFO:localstack.utils.cloudformation.template_deployer: Unable to apply change set cdk-deploy-change-set: Unable to extract attribute "Ref" from "EC2::NatGateway" model class <class 'moto.ec2.models.NatGateway'>
localstack_main | 2021-03-17T17:46:12:ERROR:cloudformation_api: Exception on / [POST]
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
localstack_main |     response = self.full_dispatch_request()
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
localstack_main |     rv = self.handle_user_exception(e)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_main |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
localstack_main |     reraise(exc_type, exc_value, tb)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack_main |     raise value
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
localstack_main |     rv = self.dispatch_request()
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
localstack_main |     return self.view_functions[rule.endpoint](**req.view_args)
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_api.py", line 549, in handle_request
localstack_main |     result = func(req_params)
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_api.py", line 438, in execute_change_set
localstack_main |     deployer.apply_change_set(change_set)
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1750, in apply_change_set
localstack_main |     change_set.changes = self.apply_changes(change_set.stack, change_set, stack_name=change_set.stack_name)
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1970, in apply_changes
localstack_main |     return self.apply_changes_in_loop(changes, existing_stack, stack_name)
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1996, in apply_changes_in_loop
localstack_main |     should_deploy = self.prepare_should_deploy_change(
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 2036, in prepare_should_deploy_change
localstack_main |     resolve_refs_recursively(stack.stack_name, resource, new_resources)
localstack_main |   File "/opt/code/localstack/localstack/utils/common.py", line 390, in func
localstack_main |     return wrapped(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1066, in resolve_refs_recursively
localstack_main |     value[key] = resolve_refs_recursively(stack_name, val, resources)
localstack_main |   File "/opt/code/localstack/localstack/utils/common.py", line 390, in func
localstack_main |     return wrapped(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1066, in resolve_refs_recursively
localstack_main |     value[key] = resolve_refs_recursively(stack_name, val, resources)
localstack_main |   File "/opt/code/localstack/localstack/utils/common.py", line 390, in func
localstack_main |     return wrapped(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 968, in resolve_refs_recursively
localstack_main |     ref = resolve_ref(stack_name, value['Ref'], resources, attribute='Ref')
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 934, in resolve_ref
localstack_main |     return determine_resource_physical_id(resource_id=ref,
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1582, in determine_resource_physical_id
localstack_main |     result = extract_resource_attribute(resource_type, {}, attribute or 'PhysicalResourceId',
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py", line 654, in extract_resource_attribute
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 797, in extract_resource_attribute
localstack_main |     raise Exception('Unable to extract attribute "%s" from "%s" model class %s' % (
localstack_main | Exception: Unable to extract attribute "Ref" from "EC2::NatGateway" model class <class 'moto.ec2.models.NatGateway'>

```

**docker-compose:**
```

version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=ec2,route53,cloudformation
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - DEFAULT_REGION=eu-central-1
      - LOCALSTACK_API_KEY=xxxxxxxxx

    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

**Comment by ismferd** [comment]
PR related:
https://github.com/whummer/moto/pull/4

**Comment by ismferd** [comment]
As far as I know that is fixed with the merge in moto before
