### ISSUE TITLE
Cannot deploy Fargate

### ISSUE THREAD

**Issue by okeeffed** [localstack/aws-cdk-local#47]
After synthesising, I cannot successfully deploy to ECS on LocalStack. I am running the Pro version of LocalStack. Stack runs on AWS.

## CDK Stack

```ts
import * as cdk from "@aws-cdk/core";
import * as ec2 from "@aws-cdk/aws-ec2";
import * as ecs from "@aws-cdk/aws-ecs";
import * as ecs_patterns from "@aws-cdk/aws-ecs-patterns";
import "dotenv/config";

export class HelloDatadogFargateStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpc = new ec2.Vpc(this, "MyVpc");

    const cluster = new ecs.Cluster(this, "MyCluster", {
      vpc: vpc,
    });

    // Create a load-balanced Fargate service and make it public
    const fargate = new ecs_patterns.ApplicationLoadBalancedFargateService(
      this,
      "MyFargateService",
      {
        cluster: cluster, // Required
        cpu: 256, // Default is 256
        desiredCount: 1, // Default is 1
        taskImageOptions: {
          image: ecs.ContainerImage.fromRegistry(
            "amazon/amazon-ecs-sample"
          ),
        },
        memoryLimitMiB: 512, // Default is 512
        publicLoadBalancer: true, // Default is false
      }
    );
  }
}
```

## Stack Trace

```s
localstack_1  | 2021-05-26T03:09:29:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "HelloDatadogFargateStack": Parameter validation failed:
localstack_1  | Missing required parameter in input: "Name" Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1825, in _run
localstack_1  |     self.do_apply_changes_in_loop(changes, stack, stack_name)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1876, in do_apply_changes_in_loop
localstack_1  |     self.apply_change(change, stack, new_resources, stack_name=stack_name)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1929, in apply_change
localstack_1  |     result = deploy_resource(resource_id, new_resources, stack_name)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 937, in deploy_resource
localstack_1  |     return execute_resource_action(resource_id, resources, stack_name, ACTION_CREATE)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1041, in execute_resource_action
localstack_1  |     result = configure_resource_via_sdk(resource_id, resources, resource_type, func, stack_name, action_name)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1164, in configure_resource_via_sdk
localstack_1  |     raise e
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1159, in configure_resource_via_sdk
localstack_1  |     result = function(**params)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
localstack_1  |     return self._make_api_call(operation_name, kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 677, in _make_api_call
localstack_1  |     request_dict = self._convert_to_request_dict(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 725, in _convert_to_request_dict
localstack_1  |     request_dict = self._serializer.serialize_to_request(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/validate.py", line 293, in serialize_to_request
localstack_1  |     raise ParamValidationError(report=report.generate_report())
localstack_1  | botocore.exceptions.ParamValidationError: Parameter validation failed:
localstack_1  | Missing required parameter in input: "Name"
localstack_1  | 
localstack_1  | 2021-05-26T03:09:30:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Value': {'Fn::GetAtt': ['MyFargateServiceLBDE830E97', 'DNSName']}} - Unable to fetch details for resource "MyFargateServiceLBDE830E97" (resolving attribute "DNSName")
localstack_1  | 2021-05-26T03:09:30:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Value': {'Fn::Join': ['', ['http://', {'Fn::GetAtt': ['MyFargateServiceLBDE830E97', 'DNSName']}]]}} - Unable to fetch details for resource "MyFargateServiceLBDE830E97" (resolving attribute "DNSName")
localstack_1  | 2021-05-26T03:09:30:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Value': {'Fn::GetAtt': ['MyFargateServiceLBDE830E97', 'DNSName']}} - Unable to fetch details for resource "MyFargateServiceLBDE830E97" (resolving attribute "DNSName")
```

**Comment by whummer** [comment]
Thanks for reporting @okeeffed . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!
