### ISSUE TITLE
does cdk-local support cdk 2.3.0?

### ISSUE THREAD

**Issue by include** [localstack/aws-cdk-local#55]
Hi,

Does cdk-local support the latest cdk version 2.3.0 (today)?

Is it the 'defacto' local dev strategy with cdk?

Cheers,
F

**Comment by whummer** [comment]
Hi @include , quick follow-up - were you able to get it working with `2.3.0` , can this issue be closed? Thanks

**Comment by nekperu15739** [comment]
the right way to check version is this one:
`npm -g list

npm -g list
/$/.nvm/versions/node/v14.18.2/lib
├── aws-cdk-local@1.65.8
├── aws-cdk@2.3.0
`
looks like not compatible, even bootstrap give an error:

`CDKToolkit |   7 | 12:22:56 AM | CREATE_FAILED        | AWS::CloudFormation::Stack | CDKToolkit

Failed resources:
 ❌  Environment aws://000000000000/us-east-1 failed bootstrapping: Error: The stack named CDKToolkit failed to deploy: CREATE_FAILED (Deployment failed)
    at Object.waitForStackDeploy (/Users/charly/.nvm/versions/node/v14.18.2/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:309:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at prepareAndExecuteChangeSet (/Users/charly/.nvm/versions/node/v14.18.2/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:351:26)
    at /Users/charly/.nvm/versions/node/v14.18.2/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:464:24
    at async Promise.all (index 0)
    at CdkToolkit.bootstrap (/Users/charly/.nvm/versions/node/v14.18.2/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:461:5)
    at initCommandLine (/Users/charly/.nvm/versions/node/v14.18.2/lib/node_modules/aws-cdk/bin/cdk.ts:267:9)
The stack named CDKToolkit failed to deploy: CREATE_FAILED (Deployment failed)
Error: The stack named CDKToolkit failed to deploy: CREATE_FAILED (Deployment failed)
    at Object.waitForStackDeploy (/Users/charly/.nvm/versions/node/v14.18.2/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:309:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at prepareAndExecuteChangeSet (/Users/charly/.nvm/versions/node/v14.18.2/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:351:26)
    at /Users/charly/.nvm/versions/node/v14.18.2/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:464:24
    at async Promise.all (index 0)
    at CdkToolkit.bootstrap (/Users/charly/.nvm/versions/node/v14.18.2/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:461:5)
    at initCommandLine (/Users/charly/.nvm/versions/node/v14.18.2/lib/node_modules/aws-cdk/bin/cdk.ts:267:9)`

**Comment by dominikschubert** [comment]
The bootstrapping issue with ECR @   localstack community should be fixed now as well.
