### ISSUE TITLE
Bootstrap Error Stack with id %s does not exist CDKToolkit

### ISSUE THREAD

**Issue by jts-mjanda** [localstack/aws-cdk-local#68]
**Versions Used**
"aws-cdk-lib": "2.22.0"
"aws-cdk-local": "^2.15.0"

**Running On**
Docker image localstack/localstack

**Error Stack**

⏳  Bootstrapping environment aws://000000000000/us-east-1...
 ❌  Environment aws://000000000000/us-east-1 failed bootstrapping: Error [ValidationError]: Stack with id %s does not exist CDKToolkit
    at Request.extractError (/opt/code/localstack/dev/dtest/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/opt/code/localstack/dev/dtest/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/opt/code/localstack/dev/dtest/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/opt/code/localstack/dev/dtest/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/opt/code/localstack/dev/dtest/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/opt/code/localstack/dev/dtest/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /opt/code/localstack/dev/dtest/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/opt/code/localstack/dev/dtest/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/opt/code/localstack/dev/dtest/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/opt/code/localstack/dev/dtest/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2022-05-01T20:33:08.561Z,
  requestId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 356.2141101632761
}

Stack with id %s does not exist CDKToolkit

**Comment by jts-mjanda** [comment]
This works without any issues on the local dev machine (windows cli doing a bootstrap to Docker localstack) but when attempting to do this in the Docker localstack we see this issue. Basically, this breaks our CircleCI implementation.

**Comment by vertti** [comment]
Same here, started appearing on several branches yesterday with no changes in dependencies.

**Comment by thrau** [comment]
thanks for reporting @jts-mjanda! we recently did some restructuring around cloudformation which may be the cause of the issue. we're looking into it now!

**Comment by thrau** [comment]
hey everyone! the fix has been deployed and should be in the localstack docker image tag `latest`.

**Comment by zExcel** [comment]
@thrau Still seems to not be working for me.
`aws-cdk-lib: 2.22.0 (build 1db4b16)`
Was able to fix it by doing what @vertti above said and switched to using `image: localstack/localstack:0.14.2`
